Projeto02/Controllers/ConsultaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Domain;
using Repository;


namespace Projeto02.Controllers
{
    public class ConsultaController : Controller
    {
        private readonly ConsultaDao _consultaDao;

        Consulta _consulta = new Consulta();

        public ConsultaController(ConsultaDao consultaDao)
        {
            _consultaDao = consultaDao;
        }

        public IActionResult CadastroConsulta()
        {
            Consulta consulta = new Consulta();
            consulta.Id = 0;

            return View();
        }

        /*

                [HttpPost]
                public async Task<IActionResult> CadastroConsulta(Consulta c)
                {
                    if (ModelState.IsValid)
                    {
                        if (c.Id != 0)
                        {
                            _consultaDao.AlterarConsulta(c);

                            return RedirectToAction("MenuPrincipalPaciente", "Paciente");


                        }
                        else
                        {
                            Consulta
                        }




                            return RedirectToAction("MenuPrincipalPaciente", "Paciente");
                        }
                        else
                        {
                            UsuarioLogado usuarioLogado = new UsuarioLogado
                            {
                                UserName = p.Login,
                                PhoneNumber = p.Senha
                            };
                            IdentityResult result = await _userManager.CreateAsync(usuarioLogado, p.Senha);
                            if (result.Succeeded)
                            {
                                await _signInManager.SignInAsync(usuarioLogado, isPersistent: false);
                                if (_pacienteDAO.CadastrarPaciente(p))
                                {
                                    return RedirectToAction("MenuPrincipalPaciente");
                                }
                                await _signInManager.SignOutAsync();
                                ModelState.AddModelError("", "Este login já está sendo utilizado");
                            }
                            AdicionarErros(result);
                        }
                    }
                    return View(p);
                }
                */







        public IActionResult ListagemConsultas()
        {
            return View();
        }




        public IActionResult AnotacaoSobreConsulta(Consulta consulta)
        {
            _consulta = consulta;
            return View(consulta);
        }

        [HttpPost]
        public IActionResult AnotacaoSobreConsulta(String anotacao)
        {
            _consulta.Anotacao = anotacao;
            if (_consultaDao.AlterarConsulta(_consulta))
            {
                return RedirectToAction("Index");
            }
            return View(_consulta);
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

Projeto02/Controllers/PacienteController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Domain;
using Repository;
using System;

namespace Projeto02.Controllers
{
    public class PacienteController : Controller
    { 
        private readonly PacienteDao _pacienteDAO;
        private readonly UserManager<UsuarioLogado> _userManager;
        private readonly SignInManager<UsuarioLogado> _signInManager;
        

        public PacienteController(PacienteDao pacienteDao
            , UserManager<UsuarioLogado> userManager
            , SignInManager<UsuarioLogado> signInManager
            )
        {
            _pacienteDAO = pacienteDao;
            _userManager = userManager;
            _signInManager = signInManager;
        }
    
        public IActionResult MenuPrincipalPaciente()
        {
            return View();
        }

        public IActionResult CadastroPaciente()
        {
            Paciente paciente = new Paciente();
            paciente.Id = 0;
            if (_userManager.GetUserName(User) != null)
            {
                paciente = _pacienteDAO.BuscarPacientePorLogin(_userManager.GetUserName(User));
                ViewBag.senha = paciente.Senha;
            }
            
            return View(paciente);
        }

        [HttpPost]
        public async Task<IActionResult> CadastroPaciente(Paciente p)
        {
            if (ModelState.IsValid)
            {
                if (p.Id != 0)
                {
                    _pacienteDAO.AlterarPaciente(p);
                    return RedirectToAction("MenuPrincipalPaciente", "Paciente");
                }
                else
                {
                    UsuarioLogado usuarioLogado = new UsuarioLogado
                    {
                        UserName = p.Login,
                        PhoneNumber = p.Senha
                    };
                    IdentityResult result = await _userManager.CreateAsync(usuarioLogado, p.Senha);
                    if (result.Succeeded)
                    {
                        await _signInManager.SignInAsync(usuarioLogado, isPersistent: false);
                        if (_pacienteDAO.CadastrarPaciente(p))
                        {
                            return RedirectToAction("MenuPrincipalPaciente");
                        }
                        await _signInManager.SignOutAsync();
                        ModelState.AddModelError("", "Este login já está sendo utilizado");
                    }
                    AdicionarErros(result);
                }
            }
            return View(p);
        }

        public void AdicionarErros(IdentityResult result)
        {
            foreach (var erro in result.Errors)
            {
                ModelState.AddModelError("", erro.Description);
            }
        }

        public async Task<IActionResult> Logout()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(Paciente p)
        {
            var result = await _signInManager.PasswordSignInAsync(p.Login, p.Senha, true, lockoutOnFailure: false);
            if (result.Succeeded)
            {
                return RedirectToAction("MenuPrincipalPaciente", "Paciente");
            }
            ModelState.AddModelError("", "Falha no Login");
            return View();
        }
        
        public async Task<IActionResult> RemoverPaciente()
        {
            Paciente paciente = _pacienteDAO.BuscarPacientePorLogin(_userManager.GetUserName(User));
            await Logout();
            _pacienteDAO.RemoverPaciente(paciente);
            return RedirectToAction("Index", "Home");
        }
    }
}

Projeto02/Views/Paciente/Cadastro.cshtml
@model Paciente

<form asp-action="Cadastrar" method="post" enctype="multipart/form-data">
    <fieldset>
        <div class="jumbotron">

            <legend>Cadastrar Paciente</legend>
            <div asp-validation-summary="ModelOnly"
                 class="text-primary"></div>
           
            
                <div class="form-group" id="Nome">
                    <label asp-for="Nome"></label>
                    <input type="text" asp-for="Nome"
                           class="form-control" />
                    <span asp-validation-for="Nome"
                          class="text-primary"></span>
                </div>

                <div asp-validation-summary="ModelOnly"
                     class="text-primary"></div>
                <div class="form-group" id="Cpf">
                    <label asp-for="Cpf"></label>
                    <input type="text" asp-for="Cpf"
                           class="form-control" />
                    <span asp-validation-for="Cpf"
                          class="text-primary"></span>
                </div>
            
                <div class="form-group" id="Idade">
                    <label asp-for="Idade"></label>
                    <input type="text" asp-for="Idade"
                           class="form-control" />
                    <span asp-validation-for="Idade"
                          class="text-primary"></span>
                </div>

                <div class="form-group" id="Telefone">
                    <label asp-for="Telefone"></label>
                    <input type="text" asp-for="Telefone"
                           class="form-control" />
                    <span asp-validation-for="Telefone"
                          class="text-primary"></span>
                </div>
                <button type="button" class="btn btn-outline-primary">Cadastrar</button>


            </div>
    
    </fieldset>
</form>

Projeto02/Views/Paciente/CadastroPaciente.cshtml
@inject Microsoft.AspNetCore.Identity.SignInManager<UsuarioLogado> SignManager
@inject Microsoft.AspNetCore.Identity.UserManager<UsuarioLogado> UserManager
@model Paciente

<form asp-action="CadastroPaciente" method="post" enctype="multipart/form-data">
    <fieldset>
        <div class="jumbotron">

            <legend>Cadastrar Paciente</legend>
            <div asp-validation-summary="ModelOnly"
                 class="text-primary"></div>

            <input type="text" asp-for="Id"
                   class="hidden" style="display: none" />

            <div class="form-group" id="Nome">
                <label asp-for="Nome"></label>
                <input type="text" asp-for="Nome"
                       class="form-control" />
                <span asp-validation-for="Nome"
                      class="text-primary"></span>
            </div>

            <div asp-validation-summary="ModelOnly"
                 class="text-primary"></div>
            <div class="form-group" id="Cpf">
                <label asp-for="Cpf"></label>
                <input type="text" asp-for="Cpf"
                       class="form-control" />
                <span asp-validation-for="Cpf"
                      class="text-primary"></span>
            </div>

            <div class="form-group" id="Idade">
                <label asp-for="Idade"></label>
                <input type="text" asp-for="Idade"
                       class="form-control" />
                <span asp-validation-for="Idade"
                      class="text-primary"></span>
            </div>

            <div class="form-group" id="Telefone">
                <label asp-for="Telefone"></label>
                <input type="text" asp-for="Telefone"
                       class="form-control" />
                <span asp-validation-for="Telefone"
                      class="text-primary"></span>
            </div>
            @if (!SignManager.IsSignedIn(User))
            {
                <legend>Dados Pessoais</legend>
                <div class="form-group" id="Email">
                    <label asp-for="Login"></label>
                    <input type="text" asp-for="Login"
                           class="form-control" />
                </div>
                <div class="form-group" id="Senha">
                    <label asp-for="Senha"></label>
                    <input type="text" asp-for="Senha"
                           class="form-control" />
                </div>
                <div class="form-group" id="ConfirmacaoSenha">
                    <label asp-for="ConfirmacaoSenha"></label>
                    <input type="text" asp-for="ConfirmacaoSenha"
                           class="form-control" />
                </div>
            }
            else
            {
                <input type="text" asp-for="Login"
                       class="hidden" style="display: none" />
                <input type="text" asp-for="Senha"
                       class="hidden" style="display: none" />
                <input type="text" asp-for="ConfirmacaoSenha"
                       class="hidden" style="display: none" value="@ViewBag.senha"/>

            }
            <button type="submit" class="btn btn-outline-primary">Cadastrar</button>


        </div>

    </fieldset>
</form>

Projeto02/Views/Paciente/Login.cshtml
@model Domain.Paciente

<fieldset>
    <div class="jumbotron">

        <h2>login</h2>
        <form asp-action="Login">
            <div class="form-group">
                <label asp-for="Login" for="exampleInputEmail1">Email</label>
                <input type="email" class="form-control" id="exampleInputEmail1"
                       aria-describedby="emailHelp" placeholder="Enter email"
                       asp-for="Login">
                <small id="emailHelp" class="form-text text-muted">Nunca compartilharemos os seus dados.</small>
                <span asp-validation-for="Login" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Senha" for="exampleInputPassword1">Senha</label>
                <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password"
                       asp-for="Senha">
                <span asp-validation-for="Senha" class="text-danger"></span>
            </div>

            <button type="submit" class="btn btn-outline-primary">Entrar</button>
            <a class="btn btn-outline-primary"
               asp-action="CadastroPaciente">Cadastrar</a>
        </form>

    </div>

</fieldset>

Projeto02/Views/Paciente/LoginTeste.cshtml
@model Domain.Paciente

@{
    ViewData["Title"] = "Login";
}

<h2>Login</h2>

<h4>Paciente</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="LoginTeste">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Login" class="control-label"></label>
                <input asp-for="Login" class="form-control" />
                <span asp-validation-for="Login" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Senha" class="control-label"></label>
                <input asp-for="Senha" class="form-control" />
                <span asp-validation-for="Senha" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="CadastroPaciente" asp-controller="Paciente">Back to List</a>
</div>

Projeto02/Views/Paciente/MenuPrincipalPaciente.cshtml
@inject Microsoft.AspNetCore.Identity.UserManager<UsuarioLogado> UserManager
@model Paciente

<fieldset>
    <div class="jumbotron">

        <legend>Seja bem vindo!</legend>
        <div asp-validation-summary="ModelOnly"
             class="text-primary"></div>

        <div class="form-group">

            <a asp-action="CadastroPaciente" class="btn btn-primary btn-lg btn-block">Alterar Cadastro</a>
            <a asp-action="RemoverPaciente" class="btn btn-primary btn-lg btn-block">Excluir Cadastro</a>
            <a asp-controller="Consulta" asp-action="CadastroConsulta" class="btn btn-primary btn-lg btn-block">Agendar Consulta</a>
            <a asp-controller="Consulta" asp-action="MenuPrincipalPaciente" class="btn btn-primary btn-lg btn-block">Alterar Consulta</a>

        </div>

</fieldset>